repos:
-   repo: local
    hooks:
    -   id: docker-compiler-check
        name: Docker C++98 Compiler Check
        entry: sh
        args:
        - -c
        - |
            docker build --tag=cpp-compile-check --file=Dockerfile .
            docker run --rm --mount type=bind,source="$(pwd)",target=/app cpp-compile-check /bin/bash -c "cd /app && make"
        language: system
        pass_filenames: false
        verbose: true
        files: \.(cpp|hpp|h)$


